import { createApp } from "vue";
import App from "./App.vue";
import Router from "@/router.js";
window.$ = window.jQuery = require("jquery");
import "bootstrap";
import "bootstrap/dist/css/bootstrap.min.css";
import "@/assets/style.css";
const app = createApp(App);
app.use(Router);
app.mount("#app");
